#!/hint/bash
# shellcheck disable=2034


DLAGENTS=('file::/usr/bin/curl -qgC - -o %o %u'
          'ftp::/usr/bin/curl -qgfC - --ftp-pasv --retry 3 --retry-delay 1 -o %o %u'
          'http::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 1 -o %o %u'
          'https::/usr/bin/curl -qgb "" -fLC - --retry 3 --retry-delay 1 -o %o %u'
          'rsync::/usr/bin/rsync --no-motd -az %u %o'
          'scp::/usr/bin/scp -C %u %o')

VCSCLIENTS=('git::git' 'hg::mercurial' 'svn::subversion')


CARCH="x86_64"
CHOST="x86_64-pc-linux-gnu"

NPROC=$(nproc)

CFLAGS="-march=native -mtune=native -O3 -pipe -flto=auto -fomit-frame-pointer -fno-plt"
CXXFLAGS="$CFLAGS -Wp,-D_GLIBCXX_ASSERTIONS"
LDFLAGS="-Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now"
LTOFLAGS="-flto=auto"

MAKEFLAGS="-j$((NPROC + 1)) -l$NPROC"

DEBUG_CFLAGS="-g1"
DEBUG_CXXFLAGS="-g1"

BUILDENV=(!distcc color !ccache !check !sign)

OPTIONS=(strip !docs !libtool !staticlibs zipman purge !debug lto autodeps)

INTEGRITY_CHECK=(sha256)

STRIP_BINARIES="--strip-all"
STRIP_SHARED="--strip-unneeded"
STRIP_STATIC="--strip-debug"

MAN_DIRS=(usr/{,local/}{,share/}{man,info})
DOC_DIRS=(usr/{,local/}{,share/}{doc,gtk-doc})
LIB_DIRS=('lib:usr/lib')
PURGE_TARGETS=(usr/{,share}/info/dir .podlist *.pod)
DBGSRCDIR="/usr/src/debug"


COMPRESSGZ=(pigz -c -f -n)
COMPRESSBZ2=(pbzip2 -c -f)
COMPRESSXZ=(xz -c -z --threads=0)
COMPRESSZST=(zstd -c -z -q --threads=0 -10)
COMPRESSLZO=(lzop -c -q)
COMPRESSLZ4=(lz4 -c -q)
COMPRESSZ=(compress -c -f)
COMPRESSLZ=(lzip -c -f)

PKGEXT='.pkg.tar.zst'
SRCEXT='.src.tar.gz'

# PACKAGER="LibreGML <1778607946@@qq.com>"
# GPGKEY=""

# vim: set ft=sh ts=2 sw=2 et:
