[options]
#RootDir     = /
#DBPath      = /var/lib/pacman/
#CacheDir    = /var/cache/pacman/pkg/
#LogFile     = /var/log/pacman.log
#GPGDir      = /etc/pacman.d/gnupg/
#HookDir     = /etc/pacman.d/hooks/
HoldPkg     = pacman glibc
#XferCommand = /usr/bin/curl -L -C - -f -o %o %u
#XferCommand = /usr/bin/wget --passive-ftp -c -O %o %u

CleanMethod = KeepCurrent
Architecture = auto

#IgnorePkg   =
#IgnoreGroup =

#NoUpgrade   =
#NoExtract   =

Color
ILoveCandy
CheckSpace
VerbosePkgLists
ParallelDownloads = 15
DownloadUser = alpm
#DisableSandboxFilesystem
#DisableSandboxSyscalls

SigLevel    = Never
LocalFileSigLevel = Never
RemoteFileSigLevel = Never

# `sudo pacman-key --init`
# `sudo pacman -S archlinux-keyring`
# `sudo pacman-key --populate archlinux`
# `pacman-key --lsign-key "farseerfc@archlinux.org"`
# `sudo pacman -S archlinuxcn-keyring`
# `sudo pacman -Syyu`

[core]
Include = /etc/pacman.d/mirrorlist

[extra]
Include = /etc/pacman.d/mirrorlist

[multilib]
Include = /etc/pacman.d/mirrorlist

[archlinuxcn]
Server = https://mirrors.aliyun.com/archlinuxcn/$arch

# Server = https://mirrors.ustc.edu.cn/archlinuxcn/$arch
# Server = https://mirrors.tuna.tsinghua.edu.cn/archlinuxcn/$arch
# Server = https://mirrors.tencent.com/archlinuxcn/$arch
# Server = https://mirrors.bfsu.edu.cn/archlinuxcn/$arch
