/
/*
/bin
/boot
/dev
/etc
/home
/home/tzgml/.config
/initrd
/lib
/lib32
/lib64
/proc
/root
/sbin
/sys
/opt
/usr
/usr/bin
/usr/include
/usr/lib
/usr/local
/usr/local/bin
/usr/local/include
/usr/local/sbin
/usr/local/share
/usr/sbin
/usr/share
/usr/src
/var
/etc/safe-rm.conf
/home/tzgml/
/srv
