# Hypridle 配置文件

general {
    lock_cmd = pidof hyprlock || hyprlock # 如果 hyprlock 未运行则启动它（每次调用 "loginctl lock-session" 时都会执行此命令）
    # unlock_cmd = killall hyprlock # 解锁时终止 hyprlock 进程（每次调用 "loginctl unlock-session" 时都会执行此命令）
    before_sleep_cmd = loginctl lock-session    # 确保系统进入睡眠前先锁定会话
    after_sleep_cmd = hyprctl dispatch dpms on # 睡眠结束后关闭屏幕显示（不是必须的，但以防万一）
    ignore_dbus_inhibit = false             # 是否忽略 dbus 发送的空闲抑制请求（常用于 Firefox 或 Steam 等应用）
}

# 如果会话已锁定，则更快地关闭屏幕
# （默认禁用）
# listener {
#     timeout = 30                            # 30 秒
#     on-timeout = pidof hyprlock && hyprctl dispatch dpms off # 如果 hyprlock 正在运行则关闭屏幕
#     on-resume = pidof hyprlock && hyprctl dispatch dpms on    # 检测到用户活动后执行的命令（在超时触发后）
# }

# 休息提醒
listener {
    timeout = 300                            # 5 分钟
    on-timeout = notify-send "宝宝玩去啦！" # 超时后执行的通知命令
    on-resume = notify-send "宝宝你回来啦！！！"  # 检测到用户活动后执行的通知命令（在超时触发后）
}

# 自动锁屏
listener {
    timeout = 1200                     # 20 分钟
    on-timeout = loginctl lock-session # 超时后执行锁定会话命令
    on-resume = notify-send "欢迎回到桌面！"  # 检测到用户活动后执行的通知命令（在超时触发后）
}

# 关闭屏幕
# （默认禁用）
# listener {
#     timeout = 630                            # 10.5 分钟
#     on-timeout = hyprctl dispatch dpms off  # 超时后关闭屏幕显示
#     on-resume = hyprctl dispatch dpms on    # 检测到用户活动后打开屏幕显示（在超时触发后）
# }

# 系统睡眠 # 默认禁用
# listener {
   # timeout = 2400                            # 40 分钟
   # on-timeout = systemctl suspend # 超时后执行系统睡眠
    # on-resume = notify-send "欢迎回到桌面！"  # 检测到用户活动后执行的通知命令（在超时触发后）
# }
