# 现在用awww, hyprpaper只用于Debian等非Arch发行版

wallpaper {
    monitor = eDP-1
    path = ~/Pictures/wallpapers/莹联国旗暗黑版.png
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = ~/Pictures/wallpapers/xiaoxin.png
    fit_mode = cover
}

wallpaper {
    monitor = 
    path = ~/Pictures/wallpapers/xiaoxin.png
    fit_mode = cover
}
