background            #0b0c15
foreground            #a9b1d6
cursor                #7aa2f7
selection_background  #485090
selection_foreground  #ffffff
color0                #15161e
color8                #565f89
color1                #f7768e
color9                #ff7a93
color2                #9ece6a
color10               #b9f27c
color3                #e0af68
color11               #ffe66d
color4                #7aa2f7
color12               #89ddff
color5                #bb9af7
color13               #c7a9ff
color6                #7dcfff
color14               #a4daff
color7                #c0caf5
color15               #ffffff
