[Journal]
Storage=persistent
SystemMaxUse=100M
SystemMaxFileSize=25M
SystemMaxFiles=5
Compress=yes
MaxLevelStore=warning
MaxLevelSyslog=warning
Seal=no
MaxRetentionSec=7day
MaxFileSec=1week
ForwardToSyslog=no
ForwardToWall=no
ForwardToConsole=no
