[Manager]
LogLevel=err
LogTarget=console
LogColor=no
LogLocation=no
LogTime=no
ShowStatus=yes
DefaultTimeoutStartSec=3s
DefaultTimeoutStopSec=3s
DefaultRestartSec=100ms
DumpCore=no
CrashChangeVT=no
CrashShell=yes
CtrlAltDelBurstAction=reboot-force
RuntimeWatchdogSec=0
RebootWatchdogSec=0
KExecWatchdogSec=0
DefaultCPUAccounting=no
DefaultBlockIOAccounting=no
DefaultMemoryAccounting=no
DefaultTasksAccounting=no
DefaultIOAccounting=no
DefaultIPAccounting=no
NoNewPrivileges=no
