# 本文件是 systemd 的一部分
#
#  systemd 是自由软件；您可以根据自由软件基金会发布的 GNU 较宽松通用公共许可证条款重新分发和/或修改它，
#  许可证版本为 2.1 或（由您选择）任何更高版本。
#
# 此文件中的条目显示编译时的默认值。本地配置应该通过以下方式创建：修改此文件（或放置在 /etc/ 中的副本，
# 如果原始文件位于 /usr/），或者通过在 /etc/systemd/system.conf.d/ 目录中创建"drop-in"配置文件。
# 通常推荐使用后一种方法。只需删除主配置文件和 /etc/ 中的所有 drop-in 文件即可恢复默认值。
#
# 使用 'systemd-analyze cat-config systemd/system.conf' 命令可以查看完整的配置内容。
#
# 详细信息请参阅 systemd-system.conf(5) 手册页。

[Manager]
LogLevel=emerg
LogTarget=null
LogColor=yes
#LogLocation=no
#LogTime=no
#DumpCore=yes
#ShowStatus=yes
#CrashChangeVT=no
#CrashShell=no
#CrashAction=freeze
#CtrlAltDelBurstAction=reboot-force
#CPUAffinity=
#NUMAPolicy=default
#NUMAMask=
RuntimeWatchdogSec=off
RuntimeWatchdogPreSec=off
#RuntimeWatchdogPreGovernor=
#RebootWatchdogSec=10min
#KExecWatchdogSec=off
#WatchdogDevice=
#CapabilityBoundingSet=
#NoNewPrivileges=no
#ProtectSystem=auto
#SystemCallArchitectures=
#TimerSlackNSec=
#StatusUnitFormat=description
#DefaultTimerAccuracySec=1min
#DefaultStandardOutput=journal
#DefaultStandardError=inherit
DefaultTimeoutStartSec=0s
DefaultTimeoutStopSec=0s
#DefaultTimeoutAbortSec=
#DefaultDeviceTimeoutSec=90s
DefaultRestartSec=0ms
#DefaultStartLimitIntervalSec=10s
#DefaultStartLimitBurst=5
#DefaultEnvironment=
#DefaultIOAccounting=no
#DefaultIPAccounting=no
#DefaultMemoryAccounting=yes
#DefaultTasksAccounting=yes
#DefaultTasksMax=15%
#DefaultLimitCPU=
#DefaultLimitFSIZE=
#DefaultLimitDATA=
#DefaultLimitSTACK=
#DefaultLimitCORE=
#DefaultLimitRSS=
DefaultLimitNOFILE=2048:2097152
#DefaultLimitAS=
#DefaultLimitNPROC=
#DefaultLimitMEMLOCK=8M
#DefaultLimitLOCKS=
#DefaultLimitSIGPENDING=
#DefaultLimitMSGQUEUE=
#DefaultLimitNICE=
#DefaultLimitRTPRIO=
#DefaultLimitRTTIME=
#DefaultMemoryPressureThresholdSec=200ms
#DefaultMemoryPressureWatch=auto
#DefaultOOMPolicy=stop
#DefaultSmackProcessLabel=
#DefaultRestrictSUIDSGID=
#ReloadLimitIntervalSec=
#ReloadLimitBurst=
